platform :ios, '9.0'

target 'ToDoRealm' do

  use_frameworks!

  # Pods for ToDoRealm

pod 'RealmSwift'
pod 'SwipeCellKit'
pod 'ChameleonFramework/Swift', :git => 'https://github.com/vicc/chameleon.git', :branch => 'master'

end
