# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pet Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pet Project

  # Rx
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxOptional'
  pod 'RxSwiftExt'
  pod 'RxDataSources'
  pod 'RxKeyboard'
  pod 'RxAnimated'
  pod 'RxKingfisher'
  pod 'RxGesture'

  # Database
  pod 'RxRealm'

  # Network
  pod 'Moya/RxSwift'

  # UI
  pod 'SnapKit'

  # DI
  pod 'Swinject'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
